name: Deploy HTML5 to release branch

on:
    workflow_dispatch:

jobs:
    export-and-push:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout release branch
                uses: actions/checkout@v4
                with:
                    ref: release
                    fetch-depth: 0
            
            -   name: Merge main into release
                run: |
                    git fetch origin main
                    git merge origin/main --no-edit || true
            
            -   name: Godot HTML5 export
                uses: acaValkyrie/godot-4-html-export@main
                with:
                    godot-version: 4.2.2
                    godot-channel: stable
            
            -   name: Push to release branch
                run: |
                    git config --global user.name "github-actions"
                    git config --global user.email "actions@github.com"

                    git add .
                    git commit -m "Deploy HTML5 export $(date + '%Y-%m-%d %H:%M:%S')"
                    git push origin release
