name: Deploy HTML5 to release branch

on:
    workflow_dispatch:

jobs:
    export-and-push:
        runs-on: ubuntu-latest

        steps:
            -   name: Checkout main branch
                uses: actions/checkout@v4
                with:
                    ref: main
                    fetch-depth: 0
            
            -   name: Godot HTML5 export
                uses: acaValkyrie/godot-4-html-export@main
                with:
                    godot-version: 4.4.1
                    godot-channel: stable
                    import-timeout-seconds: 100
            
            -   name: Push to release branch
                run: |
                    git config --global user.name "github-actions"
                    git config --global user.email "actions@github.com"

                    git fetch origin
                    git switch release || git switch -c release origin/release

                    git add .
                    git commit -m "Deploy HTML5 export $(date + '%Y-%m-%d %H:%M:%S')"
                    git push origin release
