name: Run on merge to release

on:
  workflow_dispatch:
  pull_request:
    types:
      - closed
    branches:
      - release

jobs:
  export:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Godot HTML5 export
        uses: dulvui/godot-4-html-export@v1.0.2
        with:
          godot-version: 4.2.2
      
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git pull
          git add -A .
          git commit -m "generated"
          git push origin release